'use client'
import { Plus, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { activateCiplVersion, addCiplVersion } from '@/lib/data-client'
type Draft = { description: string; quantity: string; unit: string }
const empty = (): Draft => ({ description: '', quantity: '', unit: 'PCS' })
export default function NewCiplVersionPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const [items, setItems] = useState<Draft[]>([empty()]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const update = (index: number, field: keyof Draft, value: string) => setItems((current) => current.map((item, i) => i === index ? { ...item, [field]: value } : item))
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const parsed = items.map((item, i) => ({ id: crypto.randomUUID(), lineNumber: i + 1, description: item.description.trim(), quantity: Number(item.quantity), unit: item.unit.trim().toUpperCase(), unitValue: null, currency: null, grossWeightKg: null, netWeightKg: null, countryOfOrigin: null, identifiers: [], intendedUse: null, intendedDisposal: null })); if (parsed.some((item) => !item.description || !item.unit || !(item.quantity > 0))) { setError('Setiap item membutuhkan deskripsi, quantity positif, dan unit.'); return }; setSaving(true); setError(''); try { const file = new FormData(event.currentTarget).get('file'); const sourceDocument = file instanceof File && file.size ? { id: crypto.randomUUID(), fileName: file.name, mimeType: 'application/pdf' as const, fileSize: file.size, content: file, createdAt: new Date().toISOString() } : null; const version = await addCiplVersion(params.id, { receivedAt: new Date().toISOString(), receivedBy: 'demo-user-nurul', sourceDocumentName: sourceDocument?.fileName ?? null, sourceDocument, items: parsed }); await activateCiplVersion(params.id, version.id, 'UNDER_REVIEW'); router.push(`/cipls/${params.id}`) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Versi CIPL tidak dapat disimpan.') } finally { setSaving(false) } }
  return <div className="mx-auto max-w-3xl"><form onSubmit={submit} className="card p-6 sm:p-8"><h1 className="text-2xl font-bold">Tambah versi CIPL</h1><p className="mt-2 text-sm text-slate-500">Revisi baru menyimpan seluruh daftar item sebagai snapshot.</p><div className="mt-6 space-y-4">{items.map((item, index) => <div key={index} className="grid gap-3 rounded-xl border bg-slate-50 p-4 sm:grid-cols-[1fr_9rem_8rem_auto]"><input value={item.description} onChange={(e) => update(index, 'description', e.target.value)} placeholder="Deskripsi item" className="input"/><input value={item.quantity} onChange={(e) => update(index, 'quantity', e.target.value)} min="0.0001" step="any" type="number" placeholder="Quantity" className="input"/><input value={item.unit} onChange={(e) => update(index, 'unit', e.target.value.toUpperCase())} placeholder="PCS" className="input uppercase"/><button type="button" disabled={items.length === 1} onClick={() => setItems((current) => current.filter((_, i) => i !== index))} className="rounded-lg p-2 text-rose-600 disabled:opacity-40"><Trash2 size={18}/></button></div>)}</div><button type="button" onClick={() => setItems((current) => [...current, empty()])} className="btn-secondary mt-4"><Plus size={16}/> Tambah item</button><label className="label mt-6 block">PDF CIPL (opsional)<input accept="application/pdf" type="file" name="file" className="mt-1 block w-full text-sm"/></label>{error && <p className="mt-5 text-sm text-rose-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => router.back()} className="btn-secondary">Batal</button><button disabled={saving} className="btn-primary">{saving ? 'Menyimpan...' : 'Simpan versi'}</button></div></form></div>
}
