'use client'
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { useParams } from 'next/navigation'
import { getCustomsJob, updateCustomsJob } from '@/lib/data-client'
import type { CustomsJob, CustomsJobStatus } from '@/domain/exhibition/types'
import type { CeisaStatusObservation } from '@/domain/ceisa/types'
import { StatusBadge } from '@/components/status-badge'
import { finishLoadingAfterMinimum, FormSkeleton } from '@/components/loading-skeletons'
const statuses: CustomsJobStatus[] = ['DRAFT', 'PREPARING', 'SUBMITTED', 'REGISTERED', 'RELEASED', 'COMPLETED', 'ON_HOLD', 'CANCELLED']
function notify(message: string, tone: 'success' | 'error') { window.dispatchEvent(new CustomEvent('vss:toast', { detail: { message, tone } })) }
function target(job: CustomsJob, observation: CeisaStatusObservation): CustomsJobStatus | null { const code = observation.responseCode.toUpperCase(); const name = observation.responseName.toUpperCase(); if (code.includes('REJECT') || name.includes('TOLAK')) return 'ON_HOLD'; if ((job.documentType === 'BC_2_3' || job.documentType === 'BC_2_5') && (code.includes('SPPB') || name.includes('SPPB'))) return 'RELEASED'; if (job.documentType === 'BC_3_0' && (code.includes('NPE') || name.includes('NPE'))) return 'RELEASED'; if (observation.registrationNumber || code.includes('REGISTER')) return 'REGISTERED'; return null }
export default function CustomsJobDetailPage() {
  const params = useParams<{ jobId: string }>(); const [job, setJob] = useState<CustomsJob | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [observation, setObservation] = useState<CeisaStatusObservation | null>(null); const [syncing, setSyncing] = useState(false); const loadingStartedAt = useRef(Date.now())
  useEffect(() => { loadingStartedAt.current = Date.now(); setLoading(true); getCustomsJob(params.jobId).then((loaded) => { setJob(loaded); finishLoadingAfterMinimum(loadingStartedAt.current, () => setLoading(false)) }) }, [params.jobId])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!job) return; const form = new FormData(event.currentTarget); setSaving(true); setError(''); try { const next = await updateCustomsJob(job.id, { status: String(form.get('status')) as CustomsJobStatus, ajuNumber: String(form.get('ajuNumber') || '').trim() || null, registrationNumber: String(form.get('registrationNumber') || '').trim() || null, registrationDate: String(form.get('registrationDate') || '').trim() || null, customsOfficeCode: String(form.get('customsOfficeCode') || '').trim().toUpperCase() || null, warehouseName: String(form.get('warehouseName') || '').trim() || null, notes: String(form.get('notes') || '').trim() || null }, String(form.get('reason') || '')); setJob(next); notify('Customs Job diperbarui.', 'success') } catch (caught) { const message = caught instanceof Error ? caught.message : 'Job tidak dapat disimpan.'; setError(message); notify(message, 'error') } finally { setSaving(false) } }
  async function sync() { if (!job?.ajuNumber) return; setSyncing(true); try { const response = await fetch(`/api/ceisa/status?nomorAju=${encodeURIComponent(job.ajuNumber)}`, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setObservation(body); notify('Status CEISA tersinkronkan; status lokal belum diubah.', 'success') } catch (caught) { notify(caught instanceof Error ? caught.message : 'Status CEISA tidak dapat disinkronkan.', 'error') } finally { setSyncing(false) } }
  async function apply() { if (!job || !observation) return; const next = target(job, observation); if (!next) return notify('Evidence CEISA belum memenuhi aturan transisi status.', 'error'); try { const updated = await updateCustomsJob(job.id, { status: next, registrationNumber: observation.registrationNumber ?? job.registrationNumber, registrationDate: observation.registrationDate ?? job.registrationDate }, `CEISA ${observation.responseCode}: ${observation.responseName}`); setJob(updated); notify('Hasil CEISA diterapkan ke lifecycle Job.', 'success') } catch (caught) { notify(caught instanceof Error ? caught.message : 'Hasil CEISA tidak dapat diterapkan.', 'error') } }
  if (loading || !job) return <FormSkeleton />
  return <div className="mx-auto max-w-2xl space-y-6"><form onSubmit={submit} className="card p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-slate-500">{job.documentType.replace('_', ' ')}</p><h1 className="mt-1 text-3xl font-bold">{job.jobNumber}</h1></div><StatusBadge status={job.status}/></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="label">Status<select name="status" defaultValue={job.status} className="input mt-1">{statuses.map((status) => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select></label><label className="label">Nomor aju<input name="ajuNumber" defaultValue={job.ajuNumber ?? ''} className="input mt-1" /></label><label className="label">Nomor registrasi<input name="registrationNumber" defaultValue={job.registrationNumber ?? ''} className="input mt-1" /></label><label className="label">Tanggal registrasi<input name="registrationDate" type="date" defaultValue={job.registrationDate ?? ''} className="input mt-1" /></label><label className="label">Kode kantor pabean<input name="customsOfficeCode" defaultValue={job.customsOfficeCode ?? ''} className="input mt-1" /></label><label className="label">Gudang<input name="warehouseName" defaultValue={job.warehouseName ?? ''} className="input mt-1" /></label><label className="label sm:col-span-2">Catatan<textarea name="notes" defaultValue={job.notes ?? ''} className="input mt-1 min-h-24" /></label><label className="label sm:col-span-2">Alasan perubahan status<input name="reason" className="input mt-1" /></label></div>{error && <p className="mt-4 text-sm text-rose-700">{error}</p>}<button disabled={saving} className="btn-primary mt-6">{saving ? 'Menyimpan…' : 'Simpan perubahan'}</button></form><section className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">CEISA 4.0</h2><p className="mt-1 text-sm text-slate-500">Observasi tersimpan sebagai evidence; lifecycle lokal berubah hanya setelah operator menerapkannya.</p></div><button type="button" className="btn-secondary" disabled={!job.ajuNumber || syncing} onClick={sync}>{syncing ? 'Menyinkronkan…' : 'Sinkronkan status'}</button></div>{!job.ajuNumber && <p className="mt-4 text-sm text-slate-500">Tambahkan nomor aju 26 karakter untuk sinkronisasi CEISA.</p>}{observation && <div className="mt-4 rounded-md border border-slate-200 p-4 text-sm"><p className="font-semibold">{observation.responseCode} · {observation.responseName}</p><p className="mt-1 text-slate-600">Diamati {new Date(observation.observedAt).toLocaleString('id-ID')}{observation.registrationNumber ? ` · Registrasi ${observation.registrationNumber}` : ''}</p><button type="button" className="btn-primary mt-4" onClick={apply}>Terapkan hasil CEISA</button></div>}</section></div>
}
