'use client'
import { useEffect, useState } from 'react'
import type { CeisaExchangeRateObservation, CeisaLocationReference } from '@/domain/ceisa/types'
import { Button } from '@/components/ui/button'
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'

type Props = { officeCode: string; currencyCode: string; onValue: (field: string, value: string) => void }
async function data<T>(url: string): Promise<T> { const response = await fetch(url, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? 'CEISA tidak tersedia.'); return body }
export function Bc23CeisaReferences({ officeCode, currencyCode, onValue }: Props) {
  const [query, setQuery] = useState(''); const [foreign, setForeign] = useState<CeisaLocationReference[]>([]); const [domestic, setDomestic] = useState<CeisaLocationReference[]>([]); const [tps, setTps] = useState<CeisaLocationReference[]>([]); const [rate, setRate] = useState<CeisaExchangeRateObservation | null>(null); const [notice, setNotice] = useState('')
  useEffect(() => { if (query.trim().length < 2) return setForeign([]); const timer = setTimeout(() => data<CeisaLocationReference[]>(`/api/ceisa/references?kind=foreign-port&q=${encodeURIComponent(query)}`).then(setForeign).catch(() => { setForeign([]); setNotice('Referensi CEISA tidak tersedia; gunakan input manual.') }), 300); return () => clearTimeout(timer) }, [query])
  useEffect(() => { if (!officeCode) { setDomestic([]); setTps([]); return } data<CeisaLocationReference[]>(`/api/ceisa/references?kind=domestic-port&customsOfficeCode=${encodeURIComponent(officeCode)}`).then(setDomestic).catch(() => setNotice('Referensi kantor CEISA tidak tersedia; gunakan input manual.')); data<CeisaLocationReference[]>(`/api/ceisa/references?kind=tps&customsOfficeCode=${encodeURIComponent(officeCode)}`).then(setTps).catch(() => undefined) }, [officeCode])
  async function fetchRate() { try { const value = await data<CeisaExchangeRateObservation>(`/api/ceisa/financial?action=rate&currency=${encodeURIComponent(currencyCode)}`); setRate(value) } catch (error) { setNotice(error instanceof Error ? error.message : 'Kurs CEISA tidak tersedia.') } }
  return <section className="rounded-lg border border-dashed p-4 md:col-span-2"><h3 className="font-medium">Referensi CEISA</h3><p className="mt-1 text-sm text-muted-foreground">Pemilihan mengisi kode CEISA; nilai manual tetap tersedia bila integrasi tidak aktif.</p><FieldGroup className="mt-4 grid gap-4 md:grid-cols-2"><Field><FieldLabel>Pelabuhan luar negeri</FieldLabel><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari minimal 2 karakter" />{foreign.length > 0 && <select className="input" defaultValue="" onChange={(event) => { const item = foreign.find((value) => value.code === event.target.value); if (item) onValue('kodePelMuat', item.code) }}><option value="" disabled>Pilih hasil</option>{foreign.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select>}</Field><Field><FieldLabel>Pelabuhan domestik</FieldLabel><select className="input" disabled={!officeCode || domestic.length === 0} defaultValue="" onChange={(event) => { const item = domestic.find((value) => value.code === event.target.value); if (item) onValue('kodePelBongkar', item.code) }}><option value="">{officeCode ? 'Pilih pelabuhan' : 'Isi kode kantor terlebih dahulu'}</option>{domestic.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select></Field><Field><FieldLabel>TPS / gudang</FieldLabel><select className="input" disabled={!officeCode || tps.length === 0} defaultValue="" onChange={(event) => { const item = tps.find((value) => value.code === event.target.value); if (item) onValue('kodeTps', item.code) }}><option value="">{officeCode ? 'Pilih TPS' : 'Isi kode kantor terlebih dahulu'}</option>{tps.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.name}</option>)}</select></Field><Field><FieldLabel>Kurs CEISA</FieldLabel><Button type="button" variant="outline" disabled={!/^[A-Z]{3}$/.test(currencyCode)} onClick={fetchRate}>Ambil kurs CEISA</Button>{rate && <div className="flex items-center gap-2 text-sm"><span>{rate.rate} · efektif {rate.effectiveDate}</span><Button type="button" size="sm" onClick={() => onValue('ndpbm', String(rate.rate))}>Gunakan kurs</Button></div>}</Field></FieldGroup>{notice && <FieldDescription className="mt-3">{notice}</FieldDescription>}</section>
}
