'use client'

import { useEffect, useState, type FormEvent } from 'react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'

type Settings = { configured: boolean; verificationState: string; hasCompanyId: boolean; hasIdPlatform: boolean; lastVerifiedAt: string | null }
function notify(message: string, tone: 'success' | 'error') { window.dispatchEvent(new CustomEvent('vss:toast', { detail: { message, tone } })) }
async function request(path: string, init?: RequestInit) { const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) }, cache: 'no-store' }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.error === 'string' ? body.error : 'Pengaturan CEISA tidak tersedia.'); return body }
export function CeisaConnectionSettings() {
  const [settings, setSettings] = useState<Settings | null>(null); const [unavailable, setUnavailable] = useState(false); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false)
  const load = () => request('/api/ceisa/settings').then(setSettings).catch(() => setUnavailable(true))
  useEffect(() => { load() }, [])
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await request('/api/ceisa/settings', { method: 'PUT', body: JSON.stringify({ username: String(form.get('username') ?? '').trim(), password: String(form.get('password') ?? ''), apiKey: String(form.get('apiKey') ?? ''), companyId: String(form.get('companyId') ?? '').trim() || undefined, idPlatform: String(form.get('idPlatform') ?? '').trim() || undefined }) }); await load(); setOpen(false); notify('Kredensial CEISA tersimpan.', 'success') } catch (error) { notify(error instanceof Error ? error.message : 'Kredensial CEISA tidak dapat disimpan.', 'error') } finally { setBusy(false) } }
  async function test() { setBusy(true); try { await request('/api/ceisa/settings/test', { method: 'POST', body: '{}' }); await load(); notify('Koneksi CEISA berhasil diuji.', 'success') } catch (error) { notify(error instanceof Error ? error.message : 'Koneksi CEISA gagal.', 'error') } finally { setBusy(false) } }
  if (unavailable) return <section className="card p-6"><h2 className="text-xl font-bold">Koneksi CEISA 4.0</h2><p className="mt-2 text-sm text-slate-500">Tidak tersedia: Supabase dan konfigurasi server CEISA wajib aktif. Kredensial tidak disimpan dalam mode demo.</p></section>
  return <section className="card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-bold">Koneksi CEISA 4.0</h2><p className="mt-1 text-sm text-slate-500">Status: {settings?.verificationState ?? 'Memuat…'}{settings?.lastVerifiedAt ? ` · diuji ${new Date(settings.lastVerifiedAt).toLocaleString('id-ID')}` : ''}</p></div><div className="flex gap-2"><Button type="button" variant="outline" disabled={!settings?.configured || busy} onClick={test}>Uji koneksi</Button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button type="button" disabled={busy}>{settings?.configured ? 'Ganti kredensial' : 'Konfigurasi'}</Button>} /><DialogContent><DialogHeader><DialogTitle>Kredensial CEISA</DialogTitle><DialogDescription>Setiap pembaruan wajib mengirim ulang username, password, dan API key.</DialogDescription></DialogHeader><form onSubmit={save}><FieldGroup><Field><FieldLabel htmlFor="ceisa-username">Username</FieldLabel><Input id="ceisa-username" name="username" required autoComplete="username" /></Field><Field><FieldLabel htmlFor="ceisa-password">Password</FieldLabel><Input id="ceisa-password" name="password" type="password" required autoComplete="new-password" /></Field><Field><FieldLabel htmlFor="ceisa-api-key">API key</FieldLabel><Input id="ceisa-api-key" name="apiKey" type="password" required autoComplete="off" /></Field><Field><FieldLabel htmlFor="ceisa-company">Company ID / NITKU</FieldLabel><Input id="ceisa-company" name="companyId" /><FieldDescription>Opsional; diperlukan untuk status perusahaan.</FieldDescription></Field><Field><FieldLabel htmlFor="ceisa-platform">ID platform</FieldLabel><Input id="ceisa-platform" name="idPlatform" /></Field><Button type="submit" disabled={busy}>{busy ? 'Menyimpan…' : 'Simpan kredensial'}</Button></FieldGroup></form></DialogContent></Dialog></div></div></section>
}
