'use client'

import { useEffect, useState, type FormEvent } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Save } from 'lucide-react'
import { getJob, getOperationalDetails, saveJobOperationalDetails, type JobCustomsDocument, type JobDocumentKind, type LocalJob } from '@/lib/indexeddb'

const text = (form: FormData, key: string) => String(form.get(key) || '').trim() || null
const statuses = ['NOT_STARTED', 'PREPARING', 'SUBMITTED', 'REGISTERED', 'RELEASED', 'COMPLETED', 'ON_HOLD'] as const
const labels: Record<string, string> = { NOT_STARTED: 'Belum mulai', PREPARING: 'Disiapkan', SUBMITTED: 'Diajukan', REGISTERED: 'Terdaftar', RELEASED: 'Release', COMPLETED: 'Selesai', ON_HOLD: 'Ditunda' }

function TransportFields({ prefix, title, detail }: { prefix: 'inbound' | 'outbound'; title: string; detail: ReturnType<typeof getOperationalDetails>['inbound'] }) {
  return <section className="rounded-xl border border-slate-200 p-4"><h3 className="font-semibold text-slate-900">{title}</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="label">Moda<select name={`${prefix}.mode`} defaultValue={detail.mode || ''} className="input"><option value="">Belum ditentukan</option><option value="SEA">Laut</option><option value="AIR">Udara</option><option value="LOCAL">Lokal</option></select></label><label className="label">Dokumen transport<select name={`${prefix}.documentType`} defaultValue={detail.documentType || ''} className="input"><option value="">Belum ada</option><option value="BL">B/L</option><option value="AWB">AWB</option></select></label><label className="label">Nomor B/L atau AWB<input name={`${prefix}.documentNumber`} defaultValue={detail.documentNumber || ''} className="input"/></label><label className="label">Carrier<input name={`${prefix}.carrier`} defaultValue={detail.carrier || ''} className="input"/></label><label className="label">Jadwal (ETA / ETD)<input type="date" name={`${prefix}.scheduleAt`} defaultValue={detail.scheduleAt?.slice(0, 10) || ''} className="input"/></label><label className="label">Tanggal aktual<input type="date" name={`${prefix}.actualAt`} defaultValue={detail.actualAt?.slice(0, 10) || ''} className="input"/></label></div></section>
}

function CustomsCard({ kind, detail }: { kind: 'BC_2_3' | 'BC_2_5' | 'BC_3_0'; detail: JobCustomsDocument }) {
  return <section className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">{kind.replaceAll('_', ' ')}</h3><label className="flex items-center gap-2 text-xs font-medium text-slate-600"><input type="checkbox" name={`${kind}.applicable`} defaultChecked={detail.applicable} className="h-4 w-4 accent-orange-600"/> Diperlukan</label></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="label">Status<select name={`${kind}.status`} defaultValue={detail.status} className="input">{statuses.map((status) => <option key={status} value={status}>{labels[status]}</option>)}</select></label><label className="label">Nomor aju<input name={`${kind}.ajuNumber`} defaultValue={detail.ajuNumber || ''} className="input"/></label><label className="label">Nopen<input name={`${kind}.registrationNumber`} defaultValue={detail.registrationNumber || ''} className="input"/></label><label className="label">Tanggal Nopen<input name={`${kind}.registrationDate`} type="date" defaultValue={detail.registrationDate || ''} className="input"/></label><label className="label">Gudang<input name={`${kind}.warehouseName`} defaultValue={detail.warehouseName || ''} className="input"/></label><label className="label">Lampiran PDF<input name={`attachment:${kind}`} type="file" accept="application/pdf" className="mt-2 block w-full text-sm text-slate-600"/></label></div></section>
}

export function JobEditor({ jobId }: { jobId: string }) {
  const router = useRouter(); const [job, setJob] = useState<LocalJob | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  useEffect(() => { getJob(jobId).then(setJob) }, [jobId])
  if (!job) return <p className="card p-6 text-sm text-slate-500">Memuat Job…</p>
  const loadedJob = job
  const operational = getOperationalDetails(loadedJob)
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError('')
    const transport = (prefix: 'inbound' | 'outbound') => ({ mode: (form.get(`${prefix}.mode`) || null) as ReturnType<typeof getOperationalDetails>['inbound']['mode'], documentType: (form.get(`${prefix}.documentType`) || null) as ReturnType<typeof getOperationalDetails>['inbound']['documentType'], documentNumber: text(form, `${prefix}.documentNumber`), carrier: text(form, `${prefix}.carrier`), scheduleAt: text(form, `${prefix}.scheduleAt`), actualAt: text(form, `${prefix}.actualAt`) })
    const document = (kind: 'BC_2_3' | 'BC_2_5' | 'BC_3_0'): JobCustomsDocument => ({ applicable: form.get(`${kind}.applicable`) === 'on', status: String(form.get(`${kind}.status`)) as JobCustomsDocument['status'], ajuNumber: text(form, `${kind}.ajuNumber`), registrationNumber: text(form, `${kind}.registrationNumber`), registrationDate: text(form, `${kind}.registrationDate`), warehouseName: text(form, `${kind}.warehouseName`), billing: kind === 'BC_2_5' && form.get(`${kind}.applicable`) !== 'on' ? { kind: 'NOT_APPLICABLE' } : { kind: 'NOT_READY' } })
    const attachments: Array<{ kind: JobDocumentKind; file: File }> = ['CIPL', 'BC_2_3', 'BC_2_5', 'BC_3_0'].flatMap((kind) => { const file = form.get(`attachment:${kind}`); return file instanceof File && file.size ? [{ kind: kind as JobDocumentKind, file }] : [] })
    const exhibitorName = loadedJob.exhibitor?.legalName || loadedJob.clientName
    try { await saveJobOperationalDetails(loadedJob.id, { clientName: exhibitorName, shipper: exhibitorName, agent: text(form, 'agent'), consignee: text(form, 'consignee'), notifyParty: text(form, 'notifyParty'), assignedToId: loadedJob.assignedToId, status: String(form.get('status')) as LocalJob['status'], notes: text(form, 'notes'), operational: { inbound: transport('inbound'), outbound: transport('outbound'), cipl: { status: String(form.get('cipl.status')) as typeof operational.cipl.status, referenceNumber: text(form, 'cipl.referenceNumber'), receivedAt: text(form, 'cipl.receivedAt') }, customs: { BC_2_3: document('BC_2_3'), BC_2_5: document('BC_2_5'), BC_3_0: document('BC_3_0') } } }, attachments); router.push(`/jobs/${loadedJob.id}`) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Job tidak dapat disimpan.') } finally { setSaving(false) }
  }
  return <form onSubmit={submit} className="space-y-6 pb-24"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Edit Job</p><h1 className="mt-1 text-2xl font-bold">{job.jobNumber}</h1></div><button type="button" onClick={() => router.back()} className="btn-secondary"><ArrowLeft size={16}/> Kembali</button></div>{error && <p className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}
    <section className="card p-5"><h2 className="font-semibold">Identitas dan pihak terkait</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="label">Exhibitor<input readOnly value={job.exhibitor?.legalName || job.clientName} className="input bg-slate-50 text-slate-500"/><span className="mt-1 block text-xs font-normal text-slate-500">Exhibitor berperan sebagai shipper dalam shipment pameran.</span></label><label className="label">Agent<input name="agent" defaultValue={job.agent || ''} className="input"/></label><label className="label">Consignee<input name="consignee" defaultValue={job.consignee || ''} className="input"/></label><label className="label">Notify party<input name="notifyParty" defaultValue={job.notifyParty || ''} className="input"/></label><label className="label">Status Job<select name="status" defaultValue={job.status} className="input"><option value="DRAFT">Draf</option><option value="IN_PROGRESS">Sedang diproses</option><option value="ON_HOLD">Ditunda</option><option value="COMPLETED">Selesai</option><option value="CANCELLED">Dibatalkan</option></select></label></div></section>
    <section className="card p-5"><h2 className="font-semibold">Perjalanan Job</h2><p className="mt-1 text-sm text-slate-500">Satu Job dapat mencatat perjalanan masuk dan keluar dengan moda berbeda.</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><TransportFields prefix="inbound" title="Perjalanan masuk" detail={operational.inbound}/><TransportFields prefix="outbound" title="Perjalanan keluar" detail={operational.outbound}/></div></section>
    <section className="card p-5"><h2 className="font-semibold">CIPL</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="label">Status CIPL<select name="cipl.status" defaultValue={operational.cipl.status} className="input"><option value="MISSING">Menunggu CIPL</option><option value="REQUESTED">Diminta</option><option value="RECEIVED">Diterima</option><option value="VERIFIED">Terverifikasi</option></select></label><label className="label">Referensi CIPL<input name="cipl.referenceNumber" defaultValue={operational.cipl.referenceNumber || ''} className="input"/></label><label className="label">Tanggal diterima<input name="cipl.receivedAt" type="date" defaultValue={operational.cipl.receivedAt?.slice(0, 10) || ''} className="input"/></label><label className="label">Lampiran CIPL<input name="attachment:CIPL" type="file" accept="application/pdf" className="mt-2 block w-full text-sm text-slate-600"/></label></div></section>
    <section className="card p-5"><h2 className="font-semibold">Dokumen kepabeanan</h2><p className="mt-1 text-sm text-slate-500">BC 2.5 dapat ditandai tidak diperlukan bila tidak ada barang yang dipakai atau tinggal di Indonesia.</p><div className="mt-4 grid gap-4 xl:grid-cols-3"><CustomsCard kind="BC_2_3" detail={operational.customs.BC_2_3}/><CustomsCard kind="BC_2_5" detail={operational.customs.BC_2_5}/><CustomsCard kind="BC_3_0" detail={operational.customs.BC_3_0}/></div></section>
    <section className="card p-5"><label className="label">Catatan operasional<textarea name="notes" defaultValue={job.notes || ''} className="input min-h-28"/></label></section>
    <div className="fixed bottom-0 left-0 right-0 z-10 border-t bg-white/95 px-5 py-3 backdrop-blur md:left-64"><div className="mx-auto flex max-w-[1440px] justify-end gap-3"><button type="button" onClick={() => router.back()} className="btn-secondary">Batal</button><button disabled={saving} className="btn-primary"><Save size={16}/>{saving ? 'Menyimpan…' : 'Simpan perubahan'}</button></div></div>
  </form>
}
