'use client'

import { DndContext, KeyboardSensor, PointerSensor, TouchSensor, closestCorners, useDroppable, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core'
import { SortableContext, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { AlertTriangle, GripVertical, Plus, UserRound } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { createTicket, getActiveDemoUser, listEvents, listJobs, listMyTickets, listUsers, moveAndReorderMyTickets, resolveTicketBlocker, setActiveDemoUser, setTicketBlocker, updateTicket, type LocalEvent, type LocalJob, type LocalUser, type Ticket, type TicketContext, type TicketStatus } from '@/lib/data-client'

const columns: Array<{ status: TicketStatus; label: string }> = [{ status: 'TODO', label: 'Todo' }, { status: 'PROGRESS', label: 'Progress' }, { status: 'DONE', label: 'Done' }]
const contextLabel = (context: TicketContext, events: Map<string, string>, jobs: Map<string, string>) => `${context.kind === 'EVENT' ? 'Event' : 'Job'} · ${context.kind === 'EVENT' ? events.get(context.id) : jobs.get(context.id) ?? 'Tidak ditemukan'}`

function TicketCard({ ticket, label, onEdit, onBlocker }: { ticket: Ticket; label: string; onEdit: (ticket: Ticket) => void; onBlocker: (ticket: Ticket) => void }) {
  const sortable = useSortable({ id: ticket.id, data: { status: ticket.status } })
  return <article ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition }} {...sortable.attributes} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex gap-2"><button type="button" {...sortable.listeners} aria-label={`Pindahkan ${ticket.title}`} className="mt-0.5 cursor-grab touch-none text-slate-400"><GripVertical size={16} /></button><button type="button" onClick={() => onEdit(ticket)} className="min-w-0 flex-1 text-left"><p className="font-semibold text-slate-800">{ticket.title}</p><p className="mt-1 truncate text-xs text-slate-500">{label}</p></button></div><div className="mt-3 flex items-center gap-2 text-[11px] font-medium">{ticket.priority === 'URGENT' && <span className="rounded-full bg-rose-100 px-2 py-1 text-rose-700">Urgent</span>}<button type="button" onClick={() => onBlocker(ticket)} title={ticket.blocker?.reason} className={ticket.blocker && !ticket.blocker.resolvedAt ? 'inline-flex items-center gap-1 text-amber-700' : 'inline-flex items-center gap-1 text-slate-400 hover:text-amber-700'}><AlertTriangle size={13} />Blocker</button></div></article>
}

function Column({ status, label, cards, events, jobs, onEdit, onBlocker }: { status: TicketStatus; label: string; cards: Ticket[]; events: Map<string, string>; jobs: Map<string, string>; onEdit: (ticket: Ticket) => void; onBlocker: (ticket: Ticket) => void }) {
  const { setNodeRef } = useDroppable({ id: status })
  return <section ref={setNodeRef} className="rounded-2xl bg-slate-100 p-3"><h2 className="mb-3 px-1 font-bold text-slate-700">{label} <span className="text-sm font-normal text-slate-400">{cards.length}</span></h2><SortableContext items={cards.map((ticket) => ticket.id)} strategy={verticalListSortingStrategy}><div className="min-h-28 space-y-3">{cards.length ? cards.map((ticket) => <TicketCard key={ticket.id} ticket={ticket} label={contextLabel(ticket.context, events, jobs)} onEdit={onEdit} onBlocker={onBlocker} />) : <p className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">Belum ada ticket.</p>}</div></SortableContext></section>
}

function TicketForm({ ticket, events, jobs, initialEventId, onClose, onSaved }: { ticket: Ticket | null; events: LocalEvent[]; jobs: LocalJob[]; initialEventId?: string; onClose: () => void; onSaved: () => void }) {
  const [kind, setKind] = useState<TicketContext['kind']>(ticket?.context.kind ?? 'EVENT'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const options = kind === 'EVENT' ? events.map((item) => ({ id: item.id, label: item.officialName })) : jobs.map((item) => ({ id: item.id, label: `${item.jobNumber} · ${item.clientName}` }))
  const defaultId = ticket?.context.kind === kind ? ticket.context.id : kind === 'EVENT' ? initialEventId ?? '' : ''
  async function submit(form: FormData) { setSaving(true); setError(''); try { const input = { title: String(form.get('title') || ''), description: String(form.get('description') || '') || null, context: { kind, id: String(form.get('contextId') || '') } as TicketContext, priority: form.get('urgent') === 'on' ? 'URGENT' as const : 'NORMAL' as const }; if (ticket) await updateTicket(ticket.id, input); else await createTicket(input); onSaved(); onClose() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Ticket gagal disimpan.') } finally { setSaving(false) } }
  return <div className="fixed inset-0 z-40 flex items-center justify-center bg-slate-950/40 p-4"><form action={submit} className="card w-full max-w-lg p-5"><h2 className="text-lg font-bold">{ticket ? 'Edit ticket' : 'Tambah ticket'}</h2><label className="label mt-4">Judul<input required name="title" defaultValue={ticket?.title} className="input" /></label><label className="label mt-3">Kaitkan ke<select value={kind} onChange={(event) => setKind(event.target.value as TicketContext['kind'])} className="input"><option value="EVENT">Event</option><option value="JOB">Job</option></select></label><label className="label mt-3">{kind === 'EVENT' ? 'Event' : 'Job'}<select key={`${kind}-${ticket?.id ?? 'new'}`} required name="contextId" defaultValue={defaultId} className="input"><option value="">Pilih {kind === 'EVENT' ? 'event' : 'job'}</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label><label className="label mt-3">Deskripsi<textarea name="description" defaultValue={ticket?.description ?? ''} className="input min-h-20" /></label><label className="mt-4 flex cursor-pointer items-center gap-2 text-sm font-medium text-slate-700"><input name="urgent" type="checkbox" defaultChecked={ticket?.priority === 'URGENT'} className="size-4 rounded border-slate-300 text-orange-600 focus:ring-orange-500" />Urgent</label>{error && <p className="mt-3 text-sm text-rose-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>Batal</button><button disabled={saving} className="btn-primary">{saving ? 'Menyimpan…' : 'Simpan'}</button></div></form></div>
}

export function TicketBoard({ initialEventId, openNew = false }: { initialEventId?: string; openNew?: boolean }) {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [events, setEvents] = useState<LocalEvent[]>([]); const [jobs, setJobs] = useState<LocalJob[]>([]); const [users, setUsers] = useState<LocalUser[]>([]); const [activeUser, setActiveUser] = useState<LocalUser | null>(null); const [query, setQuery] = useState(''); const [contextFilter, setContextFilter] = useState(''); const [priority, setPriority] = useState(''); const [editor, setEditor] = useState<Ticket | null | 'new'>(openNew ? 'new' : null)
  const load = async () => { const [nextTickets, nextEvents, nextJobs, nextUsers, user] = await Promise.all([listMyTickets(), listEvents(), listJobs(), listUsers(), getActiveDemoUser()]); setTickets(nextTickets); setEvents(nextEvents); setJobs(nextJobs); setUsers(nextUsers); setActiveUser(user) }
  useEffect(() => { load() }, [])
  const eventNames = useMemo(() => new Map(events.map((item) => [item.id, item.officialName])), [events]); const jobNames = useMemo(() => new Map(jobs.map((item) => [item.id, `${item.jobNumber} · ${item.clientName}`])), [jobs])
  const visible = tickets.filter((ticket) => (!query || `${ticket.title} ${contextLabel(ticket.context, eventNames, jobNames)}`.toLowerCase().includes(query.toLowerCase())) && (!contextFilter || `${ticket.context.kind}:${ticket.context.id}` === contextFilter) && (!priority || ticket.priority === priority))
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }), useSensor(TouchSensor, { activationConstraint: { delay: 150, tolerance: 5 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }))
  async function drag(event: DragEndEvent) { const id = String(event.active.id); const ticket = tickets.find((item) => item.id === id); if (!ticket || !event.over) return; const over = tickets.find((item) => item.id === String(event.over?.id)); const status = (over?.status ?? String(event.over.id)) as TicketStatus; if (!columns.some((item) => item.status === status)) return; const completion = status === 'DONE' && ticket.status !== 'DONE' ? window.prompt('Catatan hasil (wajib):') || undefined : undefined; if (status === 'DONE' && ticket.status !== 'DONE' && !completion) return; const reopen = ticket.status === 'DONE' && status !== 'DONE' ? window.prompt('Alasan membuka kembali (wajib):') || undefined : undefined; if (ticket.status === 'DONE' && status !== 'DONE' && !reopen) return; try { const ids = tickets.filter((item) => item.status === status && item.id !== id).map((item) => item.id); ids.splice(Math.max(0, over ? ids.indexOf(over.id) : ids.length), 0, id); await moveAndReorderMyTickets(id, status, ids, completion, reopen); await load() } catch (caught) { window.alert(caught instanceof Error ? caught.message : 'Ticket gagal dipindahkan.') } }
  async function blocker(ticket: Ticket) { try { if (ticket.blocker && !ticket.blocker.resolvedAt) { const resolution = window.prompt('Resolusi blocker (wajib):'); if (resolution) await resolveTicketBlocker(ticket.id, resolution) } else { const reason = window.prompt('Alasan blocker (wajib):'); if (!reason) return; const next = window.prompt('Tindak lanjut berikutnya (wajib):'); if (!next) return; await setTicketBlocker(ticket.id, reason, next) }; await load() } catch (caught) { window.alert(caught instanceof Error ? caught.message : 'Blocker gagal disimpan.') } }
  return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Ticket Saya</h1><p className="mt-1 text-sm text-slate-500">Pekerjaan pribadi Anda menurut status dan prioritas.</p></div><div className="flex flex-wrap gap-2"><label className="btn-secondary cursor-pointer"><UserRound size={16} /><select aria-label="User demo aktif" value={activeUser?.id ?? ''} onChange={async (event) => { await setActiveDemoUser(event.target.value); await load() }} className="max-w-36 bg-transparent text-sm outline-none">{users.filter((user) => user.isActive).map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><button onClick={() => setEditor('new')} className="btn-primary"><Plus size={16} />Tambah ticket</button></div></div><div className="card grid gap-3 p-4 md:grid-cols-3"><input value={query} onChange={(event) => setQuery(event.target.value)} className="input" placeholder="Cari ticket…"/><select value={contextFilter} onChange={(event) => setContextFilter(event.target.value)} className="input"><option value="">Semua konteks</option><optgroup label="Event">{events.map((event) => <option key={event.id} value={`EVENT:${event.id}`}>{event.officialName}</option>)}</optgroup><optgroup label="Job">{jobs.map((job) => <option key={job.id} value={`JOB:${job.id}`}>{job.jobNumber} · {job.clientName}</option>)}</optgroup></select><select value={priority} onChange={(event) => setPriority(event.target.value)} className="input"><option value="">Semua urgensi</option><option value="URGENT">Urgent</option><option value="NORMAL">Normal</option></select></div><DndContext sensors={sensors} collisionDetection={closestCorners} onDragEnd={drag}><div className="grid gap-4 xl:grid-cols-3">{columns.map((column) => <Column key={column.status} {...column} cards={visible.filter((ticket) => ticket.status === column.status).sort((a, b) => a.order - b.order)} events={eventNames} jobs={jobNames} onEdit={setEditor} onBlocker={blocker} />)}</div></DndContext>{editor && <TicketForm ticket={editor === 'new' ? null : editor} events={events} jobs={jobs} initialEventId={initialEventId} onClose={() => setEditor(null)} onSaved={load} />}</div>
}
