'use client'

import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { ticketStore, type LocalEvent, type LocalJob, type LocalUser, type Ticket, type TicketContext, type TicketPriority, type TicketStatus } from '@/lib/data-client'

const statuses: Array<[TicketStatus, string]> = [['TODO', 'Todo'], ['IN_PROGRESS', 'Progress'], ['DONE', 'Done'], ['CANCELLED', 'Cancel']]
const contextLabel = (context: TicketContext, events: Map<string, LocalEvent>, jobs: Map<string, LocalJob>) => context.kind === 'GENERAL' ? 'General' : context.kind === 'EVENT' ? `Event · ${events.get(context.eventId)?.alias || 'Tidak tersedia'}` : `Job · ${jobs.get(context.jobId)?.jobNumber || 'Tidak tersedia'}`
const time = (value: string) => new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))

export function TicketWorkspace({ events, jobs, users }: { events: LocalEvent[]; jobs: LocalJob[]; users: LocalUser[] }) {
  const activeUsers = users.filter((user) => user.isActive)
  const [currentUserId, setCurrentUserId] = useState(activeUsers[0]?.id || '')
  const [tickets, setTickets] = useState<Ticket[]>(() => ticketStore.listTickets())
  const [selectedId, setSelectedId] = useState<string | null>(tickets[0]?.id ?? null)
  const [showForm, setShowForm] = useState(false)
  const [editing, setEditing] = useState(false)
  const [filters, setFilters] = useState({ status: '', priority: '', context: '', assignee: '' })
  useEffect(() => ticketStore.subscribe(() => setTickets(ticketStore.listTickets())), [])
  useEffect(() => { if (selectedId && !tickets.some((ticket) => ticket.id === selectedId)) setSelectedId(tickets[0]?.id ?? null) }, [tickets, selectedId])
  const eventById = useMemo(() => new Map(events.map((event) => [event.id, event])), [events])
  const jobById = useMemo(() => new Map(jobs.map((job) => [job.id, job])), [jobs])
  const userById = useMemo(() => new Map(users.map((user) => [user.id, user])), [users])
  const selected = tickets.find((ticket) => ticket.id === selectedId) ?? null
  const filtered = tickets.filter((ticket) => (!filters.status || ticket.status === filters.status) && (!filters.priority || ticket.priority === filters.priority) && (!filters.context || ticket.context.kind === filters.context) && (!filters.assignee || (filters.assignee === 'unassigned' ? !ticket.assigneeId : ticket.assigneeId === filters.assignee)))
  const actor = currentUserId || activeUsers[0]?.id || 'local-user'
  return <div className="space-y-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold">Tickets</h1><p className="mt-2 text-sm text-slate-500">Ruang kerja per topik. Data Ticket hanya tersedia selama sesi browser ini.</p></div><div className="flex gap-2"><select className="input mt-0 w-auto" value={currentUserId} onChange={(e) => setCurrentUserId(e.target.value)} aria-label="User aktif">{activeUsers.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><button className="btn-primary" onClick={() => { setEditing(false); setShowForm(true) }}><Plus size={16}/> Ticket baru</button></div></header>
    {showForm && <TicketForm ticket={editing ? selected : null} events={events} jobs={jobs} onCancel={() => setShowForm(false)} onSave={(input) => { if (editing && selected) ticketStore.updateTicket(selected.id, input, actor); else { const ticket = ticketStore.createTicket(input, actor); setSelectedId(ticket.id) }; setShowForm(false) }} />}
    <section className="card p-4"><div className="grid gap-2 sm:grid-cols-4">{[['status', 'Status'], ['priority', 'Prioritas'], ['context', 'Konteks'], ['assignee', 'Assignee']].map(([key, label]) => <select key={key} className="input mt-0" value={filters[key as keyof typeof filters]} onChange={(e) => setFilters({ ...filters, [key]: e.target.value })}><option value="">{label}: semua</option>{key === 'status' && statuses.map(([value, text]) => <option key={value} value={value}>{text}</option>)}{key === 'priority' && <><option value="NORMAL">Normal</option><option value="URGENT">Urgent</option></>}{key === 'context' && <><option value="GENERAL">General</option><option value="EVENT">Event</option><option value="JOB">Job</option></>}{key === 'assignee' && <><option value="unassigned">Unassigned</option>{activeUsers.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</>}</select>)}</div></section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(390px,0.9fr)]"><section className="space-y-3"><h2 className="font-semibold">Semua ticket ({filtered.length})</h2>{filtered.length ? filtered.map((ticket) => <button key={ticket.id} onClick={() => { setSelectedId(ticket.id); setEditing(false) }} className={`card block w-full p-4 text-left ${selectedId === ticket.id ? 'ring-2 ring-orange-400' : 'hover:border-orange-200'}`}><div className="flex gap-3"><span className={`rounded px-2 py-1 text-xs font-bold ${ticket.priority === 'URGENT' ? 'bg-rose-100 text-rose-700' : 'bg-slate-100 text-slate-600'}`}>{ticket.priority === 'URGENT' ? 'URGENT' : 'NORMAL'}</span><span className="text-sm font-medium text-slate-500">{statuses.find(([value]) => value === ticket.status)?.[1]}</span></div><p className="mt-3 font-semibold">{ticket.title}</p><p className="mt-1 text-sm text-slate-500">{contextLabel(ticket.context, eventById, jobById)} · {ticket.assigneeId ? userById.get(ticket.assigneeId)?.name || 'User tidak tersedia' : 'Unassigned'}</p></button>) : <p className="card p-6 text-sm text-slate-500">Tidak ada ticket sesuai filter.</p>}</section>
    <section>{selected ? <TicketDetail ticket={selected} actor={actor} users={activeUsers} userById={userById} events={eventById} jobs={jobById} onEdit={() => { setEditing(true); setShowForm(true) }} onDeleted={() => setSelectedId(null)} /> : <div className="card p-8 text-sm text-slate-500">Pilih ticket untuk melihat detail.</div>}</section></div>
    <section><h2 className="mb-3 text-xl font-bold">Antrean & board personal</h2><div className="grid gap-4 lg:grid-cols-5"><BoardColumn title="Unassigned" tickets={tickets.filter((ticket) => !ticket.assigneeId)} users={userById} onSelect={setSelectedId}/>{statuses.map(([status, label]) => <BoardColumn key={status} title={label} tickets={tickets.filter((ticket) => ticket.assigneeId === actor && ticket.status === status)} users={userById} onSelect={setSelectedId}/>)}</div></section>
  </div>
}

function BoardColumn({ title, tickets, users, onSelect }: { title: string; tickets: Ticket[]; users: Map<string, LocalUser>; onSelect: (id: string) => void }) { return <div className="rounded-xl bg-slate-100 p-3"><p className="mb-3 text-sm font-bold">{title} <span className="text-slate-500">{tickets.length}</span></p><div className="space-y-2">{tickets.map((ticket) => <button key={ticket.id} onClick={() => onSelect(ticket.id)} className="w-full rounded-lg bg-white p-3 text-left text-sm shadow-sm"><p className="font-medium">{ticket.title}</p>{ticket.priority === 'URGENT' && <p className="mt-2 text-xs font-bold text-rose-700">URGENT</p>}{ticket.assigneeId && <p className="mt-2 text-xs text-slate-500">{users.get(ticket.assigneeId)?.name || 'User tidak tersedia'}</p>}</button>)}</div></div> }

function TicketForm({ ticket, events, jobs, onCancel, onSave }: { ticket: Ticket | null; events: LocalEvent[]; jobs: LocalJob[]; onCancel: () => void; onSave: (input: { title: string; description: string; context: TicketContext; priority: TicketPriority }) => void }) { const [title, setTitle] = useState(ticket?.title ?? ''); const [description, setDescription] = useState(ticket?.description ?? ''); const [kind, setKind] = useState<TicketContext['kind']>(ticket?.context.kind ?? 'GENERAL'); const [ref, setRef] = useState(ticket?.context.kind === 'EVENT' ? ticket.context.eventId : ticket?.context.kind === 'JOB' ? ticket.context.jobId : ''); const [priority, setPriority] = useState<TicketPriority>(ticket?.priority ?? 'NORMAL'); const [error, setError] = useState(''); function submit(e: FormEvent) { e.preventDefault(); if (!title.trim() || (kind !== 'GENERAL' && !ref)) return setError('Judul dan konteks yang dipilih wajib diisi'); onSave({ title, description, priority, context: kind === 'GENERAL' ? { kind } : kind === 'EVENT' ? { kind, eventId: ref } : { kind, jobId: ref } }) }; const options = kind === 'EVENT' ? events.map((item) => [item.id, item.officialName]) : jobs.map((item) => [item.id, `${item.jobNumber} · ${item.clientName}`]); return <form onSubmit={submit} className="card space-y-3 p-5"><h2 className="font-bold">{ticket ? 'Edit ticket' : 'Ticket baru'}</h2><label className="label">Judul<input className="input" value={title} onChange={(e) => setTitle(e.target.value)} /></label><label className="label">Deskripsi<textarea className="input min-h-20" value={description} onChange={(e) => setDescription(e.target.value)} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="label">Konteks<select className="input" value={kind} onChange={(e) => { setKind(e.target.value as TicketContext['kind']); setRef('') }}><option value="GENERAL">General</option><option value="EVENT">Event</option><option value="JOB">Job</option></select></label><label className="label">Prioritas<select className="input" value={priority} onChange={(e) => setPriority(e.target.value as TicketPriority)}><option value="NORMAL">Normal</option><option value="URGENT">Urgent</option></select></label></div>{kind !== 'GENERAL' && <label className="label">{kind === 'EVENT' ? 'Event' : 'Job'}<select className="input" value={ref} onChange={(e) => setRef(e.target.value)}><option value="">Pilih {kind === 'EVENT' ? 'event' : 'job'}</option>{options.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label>}{error && <p className="text-sm text-rose-600">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onCancel}>Batal</button><button className="btn-primary">Simpan</button></div></form> }

function TicketDetail({ ticket, actor, users, userById, events, jobs, onEdit, onDeleted }: { ticket: Ticket; actor: string; users: LocalUser[]; userById: Map<string, LocalUser>; events: Map<string, LocalEvent>; jobs: Map<string, LocalJob>; onEdit: () => void; onDeleted: () => void }) { const [comment, setComment] = useState(''); const timeline = ticketStore.listTicketTimeline(ticket.id); const assign = (id: string) => ticketStore.assignTicket(ticket.id, id || null, actor); return <div className="card p-5"><div className="flex gap-2"><span className={`rounded px-2 py-1 text-xs font-bold ${ticket.priority === 'URGENT' ? 'bg-rose-100 text-rose-700' : 'bg-slate-100 text-slate-600'}`}>{ticket.priority}</span><span className="text-sm text-slate-500">{contextLabel(ticket.context, events, jobs)}</span></div><h2 className="mt-3 text-xl font-bold">{ticket.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{ticket.description || 'Tidak ada deskripsi.'}</p><div className="mt-5 grid gap-3"><label className="label">Assignee<select className="input" value={ticket.assigneeId ?? ''} onChange={(e) => assign(e.target.value)}><option value="">Unassigned</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={() => assign(actor)}>Take ticket</button>{statuses.map(([status, label]) => <button key={status} className={ticket.status === status ? 'btn-primary' : 'btn-secondary'} onClick={() => ticketStore.transitionTicket(ticket.id, status, actor)}>{label}</button>)}<button className="btn-secondary" onClick={onEdit}>Edit</button><button className="btn-secondary text-rose-700" onClick={() => { if (confirm('Hapus ticket ini beserta komentar dan activity?')) { ticketStore.deleteTicket(ticket.id); onDeleted() } }} aria-label="Hapus ticket"><Trash2 size={16}/></button></div></div><section className="mt-6 border-t pt-5"><h3 className="font-semibold">Timeline</h3><div className="mt-3 space-y-3">{timeline.map((item) => <div key={item.id} className="border-l-2 border-slate-200 pl-3 text-sm">{'body' in item ? <><p>{item.body}</p><p className="mt-1 text-xs text-slate-500">{userById.get(item.authorId)?.name || 'User tidak tersedia'} · {time(item.createdAt)}</p></> : <><p className="text-slate-600">{item.summary}</p><p className="mt-1 text-xs text-slate-500">{userById.get(item.actorId)?.name || 'User tidak tersedia'} · {time(item.occurredAt)}</p></>}</div>)}</div><form className="mt-4 flex gap-2" onSubmit={(e) => { e.preventDefault(); try { ticketStore.addTicketComment(ticket.id, comment, actor); setComment('') } catch (error) { alert(error instanceof Error ? error.message : 'Komentar gagal') } }}><input className="input mt-0" value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Tulis komentar"/><button className="btn-primary">Kirim</button></form></section></div> }
