'use client'

import { DndContext, KeyboardSensor, PointerSensor, TouchSensor, closestCorners, useDroppable, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core'
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { AlertTriangle, CalendarDays, GripVertical, Plus, UserRound } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import {
  createTicket, getActiveDemoUser, listEvents, listMyTickets, listUsers, moveAndReorderMyTickets,
  setActiveDemoUser, setTicketBlocker, resolveTicketBlocker, updateTicket, type LocalEvent, type LocalUser,
  type Ticket, type TicketPriority, type TicketStatus,
} from '@/lib/data-client'

const columns: Array<{ status: TicketStatus; label: string }> = [
  { status: 'TODO', label: 'Todo' }, { status: 'PROGRESS', label: 'Progress' }, { status: 'DONE', label: 'Done' },
]
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('id-ID', { day: 'numeric', month: 'short' }).format(new Date(`${value}T00:00:00`)) : 'Tanpa tenggat'
function overdue(ticket: Ticket) { return !!ticket.dueOn && ticket.status !== 'DONE' && ticket.dueOn < new Date().toISOString().slice(0, 10) }

function TicketCard({ ticket, eventName, onEdit, onBlocker }: { ticket: Ticket; eventName: string; onEdit: (ticket: Ticket) => void; onBlocker: (ticket: Ticket) => void }) {
  const sortable = useSortable({ id: ticket.id, data: { status: ticket.status } })
  return <article ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition }} {...sortable.attributes} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
    <div className="flex gap-2"><button type="button" {...sortable.listeners} aria-label={`Pindahkan ${ticket.title}`} className="mt-0.5 cursor-grab touch-none text-slate-400"><GripVertical size={16} /></button><button type="button" onClick={() => onEdit(ticket)} className="min-w-0 flex-1 text-left"><p className="font-semibold text-slate-800">{ticket.title}</p><p className="mt-1 truncate text-xs text-slate-500">{eventName}</p></button></div>
    <div className="mt-3 flex flex-wrap items-center gap-1.5 text-[11px] font-medium"><span className={`rounded-full px-2 py-1 ${ticket.priority === 'URGENT' ? 'bg-rose-100 text-rose-700' : 'bg-slate-100 text-slate-600'}`}>{ticket.priority === 'URGENT' ? 'Urgent' : 'Normal'}</span><span className={`${overdue(ticket) ? 'text-rose-700' : 'text-slate-500'} inline-flex items-center gap-1`}><CalendarDays size={12} />{formatDate(ticket.dueOn)}</span><button type="button" onClick={() => onBlocker(ticket)} title={ticket.blocker?.reason} className={ticket.blocker && !ticket.blocker.resolvedAt ? 'inline-flex items-center gap-1 text-amber-700' : 'text-slate-400 hover:text-amber-700'}><AlertTriangle size={13} />{ticket.blocker && !ticket.blocker.resolvedAt ? 'Blocker' : 'Blocker'}</button></div>
  </article>
}

function BoardColumn({ status, label, cards, eventNames, onEdit, onBlocker }: { status: TicketStatus; label: string; cards: Ticket[]; eventNames: Map<string, string>; onEdit: (ticket: Ticket) => void; onBlocker: (ticket: Ticket) => void }) {
  const { setNodeRef } = useDroppable({ id: status })
  return <section ref={setNodeRef} className="rounded-2xl bg-slate-100 p-3"><h2 className="mb-3 px-1 font-bold text-slate-700">{label} <span className="text-sm font-normal text-slate-400">{cards.length}</span></h2><SortableContext items={cards.map((ticket) => ticket.id)} strategy={verticalListSortingStrategy}><div className="min-h-28 space-y-3">{cards.length ? cards.map((ticket) => <TicketCard key={ticket.id} ticket={ticket} eventName={eventNames.get(ticket.context.id) || 'Event tidak ditemukan'} onEdit={onEdit} onBlocker={onBlocker}/>) : <p className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">Belum ada ticket.</p>}</div></SortableContext></section>
}

function TicketForm({ ticket, events, initialEventId, onClose, onSaved }: { ticket: Ticket | null; events: LocalEvent[]; initialEventId?: string; onClose: () => void; onSaved: () => void }) {
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  async function submit(form: FormData) { setSaving(true); setError(''); try { const input = { title: String(form.get('title') || ''), description: String(form.get('description') || '') || null, eventId: String(form.get('eventId') || ''), dueOn: String(form.get('dueOn') || '') || null, priority: String(form.get('priority') || 'NORMAL') as TicketPriority }; ticket ? await updateTicket(ticket.id, input) : await createTicket(input); onSaved(); onClose() } catch (e) { setError(e instanceof Error ? e.message : 'Ticket gagal disimpan.') } finally { setSaving(false) } }
  return <div className="fixed inset-0 z-40 flex items-center justify-center bg-slate-950/40 p-4"><form action={submit} className="card w-full max-w-lg p-5"><h2 className="text-lg font-bold">{ticket ? 'Edit ticket' : 'Tambah ticket'}</h2><label className="label mt-4">Judul<input required name="title" defaultValue={ticket?.title} className="input" /></label><label className="label mt-3">Event<select required name="eventId" defaultValue={ticket?.context.id ?? initialEventId ?? ''} className="input"><option value="">Pilih event</option>{events.map((event) => <option key={event.id} value={event.id}>{event.officialName}</option>)}</select></label><label className="label mt-3">Deskripsi<textarea name="description" defaultValue={ticket?.description ?? ''} className="input min-h-20" /></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="label">Tenggat<input name="dueOn" type="date" defaultValue={ticket?.dueOn ?? ''} className="input" /></label><label className="label">Urgensi<select name="priority" defaultValue={ticket?.priority ?? 'NORMAL'} className="input"><option value="NORMAL">Normal</option><option value="URGENT">Urgent</option></select></label></div>{error && <p className="mt-3 text-sm text-rose-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>Batal</button><button disabled={saving} className="btn-primary">{saving ? 'Menyimpan…' : 'Simpan'}</button></div></form></div>
}

export function TicketBoard({ initialEventId, openNew = false }: { initialEventId?: string; openNew?: boolean }) {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [events, setEvents] = useState<LocalEvent[]>([]); const [users, setUsers] = useState<LocalUser[]>([]); const [activeUser, setActiveUser] = useState<LocalUser | null>(null); const [query, setQuery] = useState(''); const [eventFilter, setEventFilter] = useState(initialEventId ?? ''); const [priority, setPriority] = useState(''); const [due, setDue] = useState(''); const [editor, setEditor] = useState<Ticket | null | 'new'>(openNew ? 'new' : null)
  const load = async () => { const [loadedTickets, loadedEvents, loadedUsers, user] = await Promise.all([listMyTickets(), listEvents(), listUsers(), getActiveDemoUser()]); setTickets(loadedTickets); setEvents(loadedEvents); setUsers(loadedUsers); setActiveUser(user) }
  useEffect(() => { load() }, [])
  const eventNames = useMemo(() => new Map(events.map((event) => [event.id, event.officialName])), [events])
  const visible = tickets.filter((ticket) => (!query || `${ticket.title} ${eventNames.get(ticket.context.id) || ''}`.toLowerCase().includes(query.toLowerCase())) && (!eventFilter || ticket.context.id === eventFilter) && (!priority || ticket.priority === priority) && (!due || (due === 'overdue' ? overdue(ticket) : due === 'none' ? !ticket.dueOn : !!ticket.dueOn)))
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }), useSensor(TouchSensor, { activationConstraint: { delay: 150, tolerance: 5 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }))
  async function handleDragEnd(event: DragEndEvent) { const id = String(event.active.id); const ticket = tickets.find((item) => item.id === id); if (!ticket || !event.over) return; const overTicket = tickets.find((item) => item.id === String(event.over?.id)); const target = (overTicket?.status ?? String(event.over.id)) as TicketStatus; if (!columns.some((column) => column.status === target)) return; let completion: string | undefined; let reopen: string | undefined; if (target === 'DONE' && ticket.status !== 'DONE') { completion = window.prompt('Catatan hasil (wajib):') || undefined; if (!completion) return } if (ticket.status === 'DONE' && target !== 'DONE') { reopen = window.prompt('Alasan membuka kembali (wajib):') || undefined; if (!reopen) return } try { const column = tickets.filter((item) => item.status === target && item.id !== id).map((item) => item.id); const position = overTicket ? column.indexOf(overTicket.id) : column.length; column.splice(Math.max(0, position), 0, id); await moveAndReorderMyTickets(id, target, column, completion, reopen); await load() } catch (e) { window.alert(e instanceof Error ? e.message : 'Ticket gagal dipindahkan.') } }
  async function handleBlocker(ticket: Ticket) { try { if (ticket.blocker && !ticket.blocker.resolvedAt) { const resolution = window.prompt('Resolusi blocker (wajib):'); if (resolution) await resolveTicketBlocker(ticket.id, resolution) } else { const reason = window.prompt('Alasan blocker (wajib):'); if (!reason) return; const nextAction = window.prompt('Tindak lanjut berikutnya (wajib):'); if (!nextAction) return; await setTicketBlocker(ticket.id, reason, nextAction) } await load() } catch (e) { window.alert(e instanceof Error ? e.message : 'Blocker gagal disimpan.') } }
  return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Ticket Saya</h1><p className="mt-1 text-sm text-slate-500">Pekerjaan pribadi Anda menurut status dan prioritas.</p></div><div className="flex flex-wrap gap-2"><label className="btn-secondary cursor-pointer"><UserRound size={16} /><select aria-label="User demo aktif" value={activeUser?.id ?? ''} onChange={async (e) => { await setActiveDemoUser(e.target.value); await load() }} className="max-w-36 bg-transparent text-sm outline-none">{users.filter((user) => user.isActive).map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><button onClick={() => setEditor('new')} className="btn-primary"><Plus size={16} /> Tambah ticket</button></div></div><div className="card grid gap-3 p-4 md:grid-cols-4"><input value={query} onChange={(e) => setQuery(e.target.value)} className="input" placeholder="Cari ticket…"/><select value={eventFilter} onChange={(e) => setEventFilter(e.target.value)} className="input"><option value="">Semua Event</option>{events.map((event) => <option key={event.id} value={event.id}>{event.officialName}</option>)}</select><select value={priority} onChange={(e) => setPriority(e.target.value)} className="input"><option value="">Semua urgensi</option><option value="URGENT">Urgent</option><option value="NORMAL">Normal</option></select><select value={due} onChange={(e) => setDue(e.target.value)} className="input"><option value="">Semua tenggat</option><option value="overdue">Terlambat</option><option value="has">Dengan tenggat</option><option value="none">Tanpa tenggat</option></select></div><DndContext sensors={sensors} collisionDetection={closestCorners} onDragEnd={handleDragEnd}><div className="grid gap-4 xl:grid-cols-3">{columns.map((column) => <BoardColumn key={column.status} {...column} cards={visible.filter((ticket) => ticket.status === column.status).sort((a, b) => a.order - b.order)} eventNames={eventNames} onEdit={setEditor} onBlocker={handleBlocker}/>)}</div></DndContext>{editor && <TicketForm ticket={editor === 'new' ? null : editor} events={events} initialEventId={initialEventId} onClose={() => setEditor(null)} onSaved={load}/>}</div>
}
