'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, CalendarDays, FileText, Pencil, ShipWheel } from 'lucide-react'
import { getJob, getOperationalDetails, type LocalJob } from '@/lib/data-client'
import { StatusBadge } from '@/components/status-badge'

const date = (value: string | null) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(value)) : 'Belum diisi'
const label = (value: string) => value.replaceAll('_', ' ')

function Info({ label: title, value }: { label: string; value: string | null | undefined }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{title}</dt><dd className="mt-1 text-sm font-medium text-slate-800">{value || '—'}</dd></div> }

export default function JobDetail({ params }: { params: { id: string } }) {
  const [job, setJob] = useState<LocalJob | null>(null); useEffect(() => { getJob(params.id).then(setJob) }, [params.id])
  if (!job) return <p className="card p-6 text-sm text-slate-500">Memuat Job…</p>
  const details = getOperationalDetails(job); const completed = Object.values(details.customs).filter((item) => item.applicable && item.status === 'COMPLETED').length; const required = Object.values(details.customs).filter((item) => item.applicable).length; const invoiceItems = details.invoiceItems ?? []
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/jobs" className="inline-flex items-center gap-1 text-sm font-medium text-slate-500 hover:text-orange-700"><ArrowLeft size={16}/> Kembali ke Jobs</Link><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold tracking-tight">{job.jobNumber}</h1><StatusBadge status={job.status}/></div><p className="mt-2 text-sm text-slate-500">{job.exhibitor?.legalName || job.shipper || job.clientName} · {job.agent || 'Agent belum diisi'}</p></div><Link href={`/jobs/${job.id}/edit`} className="btn-primary"><Pencil size={16}/> Edit Job</Link></div>
    <section className="rounded-2xl border border-orange-200 bg-orange-50 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-orange-900">Kesiapan Job</p><p className="mt-1 text-sm text-orange-800">CIPL: {label(details.cipl.status)} · Dokumen BC selesai: {completed}/{required}</p></div><div className="h-2 w-full max-w-xs overflow-hidden rounded-full bg-orange-100"><div className="h-full rounded-full bg-orange-600" style={{ width: `${required ? Math.round((completed / required) * 100) : 0}%` }}/></div></div></section>
    <div className="grid gap-6 xl:grid-cols-3"><div className="space-y-6 xl:col-span-2"><section className="card p-5"><h2 className="font-semibold">Identitas Job</h2><dl className="mt-4 grid gap-5 sm:grid-cols-2"><Info label="Exhibitor" value={job.exhibitor?.legalName || job.clientName}/><Info label="Peran dalam shipment" value="Shipper"/><Info label="Agent" value={job.agent}/><Info label="Consignee" value={job.consignee}/><Info label="Notify party" value={job.notifyParty}/><Info label="PIC" value={job.assignedTo?.name}/></dl></section>
      <section className="card p-5"><div className="flex items-center gap-2"><ShipWheel size={20} className="text-orange-600"/><h2 className="font-semibold">Perjalanan</h2></div><div className="mt-4 grid gap-4 md:grid-cols-2">{([['Masuk', details.inbound], ['Keluar', details.outbound]] as const).map(([title, leg]) => <div key={title} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold text-slate-800">{title}</p><p className="mt-2 text-sm text-slate-600">{leg.mode ? `${leg.mode} · ${leg.documentType || 'tanpa dokumen'}` : 'Belum direncanakan'}</p><p className="mt-1 text-sm font-medium">{leg.documentNumber || 'Nomor dokumen belum diisi'}</p><p className="mt-3 text-xs text-slate-500">Jadwal: {date(leg.scheduleAt)} · Aktual: {date(leg.actualAt)}</p></div>)}</div></section>
      <section className="card p-5"><div className="flex items-center gap-2"><FileText size={20} className="text-orange-600"/><h2 className="font-semibold">Dokumen kepabeanan</h2></div><div className="mt-4 grid gap-4 md:grid-cols-3">{(Object.entries(details.customs) as Array<[keyof typeof details.customs, typeof details.customs.BC_2_3]>).map(([kind, document]) => <div key={kind} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-2"><p className="font-semibold">{label(kind)}</p><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${!document.applicable ? 'bg-slate-100 text-slate-500' : document.status === 'COMPLETED' ? 'bg-emerald-100 text-emerald-800' : 'bg-blue-100 text-blue-800'}`}>{document.applicable ? label(document.status) : 'Tidak diperlukan'}</span></div>{document.applicable && <dl className="mt-4 space-y-3"><Info label="Nomor aju" value={document.ajuNumber}/><Info label="Nopen" value={document.registrationNumber}/><Info label="Tanggal Nopen" value={date(document.registrationDate)}/><Info label="Gudang" value={document.warehouseName}/></dl>}</div>)}</div></section></div>
      <aside className="space-y-6"><section className="card p-5"><div className="flex items-center gap-2"><CalendarDays size={20} className="text-orange-600"/><h2 className="font-semibold">CIPL</h2></div><p className="mt-4 text-sm font-medium text-slate-800">{label(details.cipl.status)}</p><p className="mt-1 text-sm text-slate-500">{details.cipl.referenceNumber || 'Referensi belum diisi'}</p><p className="mt-4 text-xs text-slate-500">Diterima: {date(details.cipl.receivedAt)}</p></section><section className="card p-5"><h2 className="font-semibold">Invoice hasil parse</h2><p className="mt-3 text-sm font-medium text-slate-800">No. Invoice: {details.invoiceNumber || '-'}</p>{invoiceItems.length ? <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="pb-2 pr-3">Barang</th><th className="pb-2 pr-3">HS</th><th className="pb-2 text-right">Harga</th></tr></thead><tbody>{invoiceItems.map((item, index) => <tr key={`${item.description}-${index}`} className="border-t"><td className="py-2 pr-3 text-slate-700">{item.description}</td><td className="py-2 pr-3 text-slate-600">{item.hsCode || '-'}</td><td className="py-2 text-right text-slate-700">{item.currency || ''} {item.lineTotal ?? item.unitPrice ?? '-'}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-sm text-slate-500">Belum ada baris barang yang berhasil diekstrak.</p>}</section><section className="card p-5"><h2 className="font-semibold">Catatan</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{job.notes || 'Belum ada catatan operasional.'}</p></section></aside></div>
  </div>
}
