import Link from 'next/link'
import { notFound } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import { StatusBadge } from '@/components/status-badge'
import { JobDetailActions } from '@/components/job-detail-actions'
import { Stages } from '@/components/stages'
import { formatDate } from '@/lib/utils'
export const dynamic='force-dynamic'
export default async function JobDetail({params}:{params:{id:string}}){const job=await prisma.job.findUnique({where:{id:params.id},include:{assignedTo:true,stages:{orderBy:{order:'asc'}},documents:{include:{uploadedBy:true},orderBy:{createdAt:'desc'}}}});if(!job)notFound();return <><div className="mb-7 flex items-start justify-between"><div><div className="flex gap-2"><h1 className="text-2xl font-bold">{job.jobNumber}</h1><StatusBadge status={job.status}/></div><p className="mt-1 text-sm text-slate-500">Diperbarui {formatDate(job.updatedAt)}</p></div><Link href={`/jobs/${job.id}/edit`} className="btn-secondary">Edit job</Link></div><div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><section className="card p-5"><h2 className="font-semibold">Informasi shipment</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Klien</dt><dd className="mt-1 font-medium">{job.clientName}</dd></div><div><dt className="text-slate-500">Tipe</dt><dd className="mt-1 font-medium">{job.type}</dd></div><div><dt className="text-slate-500">AWB / BL</dt><dd className="mt-1 font-medium">{job.awbNumber||job.blNumber||'—'}</dd></div><div><dt className="text-slate-500">PIC</dt><dd className="mt-1 font-medium">{job.assignedTo?.name||'Belum ditugaskan'}</dd></div></dl>{job.notes&&<p className="mt-5 rounded-lg bg-slate-50 p-3 text-sm text-slate-600">{job.notes}</p>}</section><Stages jobId={job.id} initial={job.stages}/><section className="card p-5"><h2 className="font-semibold">Dokumen</h2><div className="mt-3 space-y-2">{job.documents.map(doc=><a key={doc.id} href={doc.fileUrl} target="_blank" className="flex justify-between rounded-lg border p-3 text-sm hover:bg-slate-50"><span>{doc.label} <span className="text-slate-500">· {doc.fileName}</span></span><span className="text-slate-500">{doc.uploadedBy.name}</span></a>)}{!job.documents.length&&<p className="text-sm text-slate-500">Belum ada dokumen. Upload tersedia lewat API endpoint.</p>}</div></section></div><aside><JobDetailActions id={job.id} token={job.trackingToken}/></aside></div></>}
