'use client'

import { useEffect, useState } from 'react'
import { CalendarDays, MapPin, Plus, X } from 'lucide-react'
import { EventForm } from '@/components/event-form'
import { listEvents, type LocalEvent } from '@/lib/indexeddb'

export default function EventsPage() {
    const [events, setEvents] = useState<LocalEvent[]>([])
    const [showNewEvent, setShowNewEvent] = useState(false)
    const reloadEvents = () => { listEvents().then(setEvents) }
    useEffect(() => { reloadEvents() }, [])

    return <>
        <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-bold tracking-tight">Events</h1><p className="mt-2 text-sm text-slate-500">Kelola data event yang tersimpan di browser.</p></div><button type="button" onClick={() => setShowNewEvent(true)} className="btn-primary"><Plus size={16} /> New Event</button></div><div className="grid gap-4 sm:grid-cols-3"><article className="card p-5"><CalendarDays className="text-orange-600" size={20} /><p className="mt-4 text-sm text-slate-500">Total event</p><p className="mt-1 text-3xl font-bold">{events.length}</p></article><article className="card p-5"><MapPin className="text-blue-600" size={20} /><p className="mt-4 text-sm text-slate-500">Venue terdaftar</p><p className="mt-1 text-3xl font-bold">{new Set(events.map((event) => event.venueId)).size}</p></article><article className="card p-5"><CalendarDays className="text-emerald-600" size={20} /><p className="mt-4 text-sm text-slate-500">Event mendatang</p><p className="mt-1 text-3xl font-bold">{events.filter((event) => new Date(event.endsAt) >= new Date()).length}</p></article></div><section className="card overflow-hidden"><div className="border-b px-5 py-4"><h2 className="font-semibold">Event terbaru</h2><p className="mt-1 text-xs text-slate-500">Tersimpan di perangkat ini</p></div><div className="divide-y">{events.slice(0, 5).map((event) => <div key={event.id} className="p-5"><p className="font-semibold">{event.officialName}</p><p className="mt-1 text-sm text-slate-500">{event.alias || 'Tanpa alias'} · {event.eventOrganizer?.legalName}</p><p className="mt-2 flex items-center gap-1 text-sm text-slate-600"><MapPin size={14} /> {event.venue?.officialName}</p><p className="mt-1 text-xs text-slate-500">{new Date(event.startsAt).toLocaleString('id-ID')} - {new Date(event.endsAt).toLocaleString('id-ID')}</p></div>)}{!events.length && <div className="p-12 text-center"><p className="font-medium">Belum ada event</p><p className="mt-1 text-sm text-slate-500">Buat event pertama untuk mulai.</p></div>}</div></section></div>
        {showNewEvent && <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/40 p-4 sm:p-8" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setShowNewEvent(false) }}><div role="dialog" aria-modal="true" aria-labelledby="new-event-title" className="card flex max-h-[calc(100vh-2rem)] min-h-0 w-full max-w-4xl flex-col overflow-hidden"><div className="flex shrink-0 items-center justify-between border-b px-6 py-5 sm:px-8"><div><h2 id="new-event-title" className="text-xl font-bold">Form Input Pameran</h2></div><button type="button" onClick={() => setShowNewEvent(false)} aria-label="Tutup form event" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-black"><X size={20} /></button></div><EventForm onSaved={() => { setShowNewEvent(false); reloadEvents() }} onCancel={() => setShowNewEvent(false)} /></div></div>}
    </>
}