'use client'
import { useEffect, useState, type FormEvent } from 'react'
import { useSearchParams, useParams, useRouter } from 'next/navigation'
import { createShipment, listCiplVersions } from '@/lib/indexeddb'
import type { CiplVersion } from '@/domain/exhibition/types'
export default function NewShipmentPage() {
  const params = useParams<{ id: string }>(); const search = useSearchParams(); const router = useRouter(); const versionId = search.get('version')
  const [version, setVersion] = useState<CiplVersion | null>(null); const [quantities, setQuantities] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { if (versionId) listCiplVersions(params.id).then((versions) => setVersion(versions.find((item) => item.id === versionId) ?? null)) }, [params.id, versionId])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const documentType = String(form.get('documentType')) as 'BL' | 'AWB'; const documentNumber = String(form.get('documentNumber') ?? '').trim(); if (!versionId || !version || !documentNumber) { setError('Versi aktif dan nomor dokumen wajib tersedia.'); return }; const allocations = version.items.flatMap((item) => { const quantity = Number(quantities[item.id] || 0); return quantity > 0 ? [{ ciplVersionId: version.id, ciplItemId: item.id, quantity, unit: item.unit }] : [] }); if (!allocations.length) { setError('Alokasikan minimal satu item ke shipment.'); return }; setSaving(true); setError(''); try { await createShipment(params.id, versionId, { documentType, documentNumber, shipmentMode: documentType === 'BL' ? String(form.get('shipmentMode') || '') as 'FCL' | 'LCL' | null : null, direction: String(form.get('direction')) as 'IMPORT' | 'EXPORT', shipper: null, consignee: null, notifyParty: null, carrier: null, etaOrEtd: null, origin: null, destination: null, attachment: null, status: 'DRAFT' }, allocations); router.push(`/cipls/${params.id}`) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Shipment tidak dapat disimpan.') } finally { setSaving(false) } }
  return <div className="mx-auto max-w-3xl"><form onSubmit={submit} className="card p-6 sm:p-8"><h1 className="text-2xl font-bold">Buat shipment</h1><p className="mt-2 text-sm text-slate-500">Pilih quantity tiap item yang benar-benar dikirim dalam B/L atau AWB ini.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="label">Jenis dokumen<select name="documentType" className="input mt-1"><option value="AWB">AWB</option><option value="BL">B/L</option></select></label><label className="label">Nomor dokumen<input required name="documentNumber" className="input mt-1"/></label><label className="label">Arah<select name="direction" className="input mt-1"><option value="IMPORT">Impor</option><option value="EXPORT">Ekspor</option></select></label><label className="label">Mode B/L (opsional)<select name="shipmentMode" className="input mt-1"><option value="">—</option><option value="FCL">FCL</option><option value="LCL">LCL</option></select></label></div><section className="mt-7"><h2 className="font-semibold">Alokasi item</h2>{version ? <div className="mt-3 divide-y rounded-xl border">{version.items.map((item) => <label key={item.id} className="grid grid-cols-[1fr_8rem] items-center gap-4 p-4"><span><span className="block font-medium">{item.lineNumber}. {item.description}</span><span className="text-xs text-slate-500">Tersedia: {item.quantity} {item.unit}</span></span><input value={quantities[item.id] ?? ''} onChange={(e) => setQuantities((current) => ({ ...current, [item.id]: e.target.value }))} min="0" max={item.quantity} step="any" type="number" placeholder={item.unit} className="input"/></label>)}</div> : <p className="mt-3 text-sm text-slate-500">Memuat item CIPL...</p>}</section>{error && <p className="mt-5 text-sm text-rose-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => router.back()} className="btn-secondary">Batal</button><button disabled={saving || !version} className="btn-primary">{saving ? 'Menyimpan...' : 'Simpan shipment'}</button></div></form></div>
}
