'use client'
import { useEffect, useState, type FormEvent } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { createCustomsJob, getShipment } from '@/lib/indexeddb'
import type { Shipment } from '@/domain/exhibition/types'
export default function NewCustomsJobPage() {
  const params = useParams<{ id: string; shipmentId: string }>(); const router = useRouter(); const [shipment, setShipment] = useState<Shipment | null>(null); const [quantities, setQuantities] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { getShipment(params.shipmentId).then(setShipment) }, [params.shipmentId])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (!shipment) return; const allocations = shipment.allocations.flatMap((item) => { const quantity = Number(quantities[item.ciplItemId] || 0); return quantity > 0 ? [{ ciplItemId: item.ciplItemId, quantity, unit: item.unit }] : [] }); if (!allocations.length) { setError('Alokasikan minimal satu item ke Job.'); return }; setSaving(true); setError(''); try { await createCustomsJob(params.shipmentId, { documentType: String(form.get('documentType')) as 'BC_2_3' | 'BC_2_5' | 'BC_3_0', ajuNumber: String(form.get('ajuNumber') || '').trim() || null, registrationNumber: null, registrationDate: null, warehouseId: null, warehouseName: null, assignedToId: null, billing: { kind: 'NOT_READY' }, status: 'DRAFT', attachments: [], notes: String(form.get('notes') || '').trim() || null }, allocations); router.push(`/cipls/${params.id}/shipments/${params.shipmentId}`) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Customs Job tidak dapat disimpan.') } finally { setSaving(false) } }
  return <div className="mx-auto max-w-3xl"><form onSubmit={submit} className="card p-6 sm:p-8"><h1 className="text-2xl font-bold">Buat Customs Job</h1><p className="mt-2 text-sm text-slate-500">Satu Job merekam satu dokumen BC dan mengambil item dari Shipment ini.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="label">Jenis dokumen BC<select name="documentType" className="input mt-1"><option value="BC_2_3">BC 2.3</option><option value="BC_2_5">BC 2.5</option><option value="BC_3_0">BC 3.0</option></select></label><label className="label">Nomor aju (opsional)<input name="ajuNumber" className="input mt-1"/></label><label className="label sm:col-span-2">Catatan<textarea name="notes" className="input mt-1 min-h-24"/></label></div><section className="mt-7"><h2 className="font-semibold">Alokasi item Shipment</h2>{shipment ? <div className="mt-3 divide-y rounded-xl border">{shipment.allocations.map((item) => <label key={item.ciplItemId} className="grid grid-cols-[1fr_8rem] items-center gap-4 p-4"><span><span className="block font-medium">Item {item.ciplItemId.slice(0, 8)}</span><span className="text-xs text-slate-500">Tersedia di shipment: {item.quantity} {item.unit}</span></span><input value={quantities[item.ciplItemId] ?? ''} onChange={(e) => setQuantities((current) => ({ ...current, [item.ciplItemId]: e.target.value }))} min="0" max={item.quantity} step="any" type="number" placeholder={item.unit} className="input"/></label>)}</div> : <p className="mt-3 text-sm text-slate-500">Memuat alokasi shipment...</p>}</section>{error && <p className="mt-5 text-sm text-rose-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => router.back()} className="btn-secondary">Batal</button><button disabled={saving || !shipment} className="btn-primary">{saving ? 'Menyimpan...' : 'Simpan Job'}</button></div></form></div>
}
