'use client'
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { createCustomsJob, getShipment } from '@/lib/data-client'
import type { Shipment } from '@/domain/exhibition/types'
import { finishLoadingAfterMinimum, ListSkeleton } from '@/components/loading-skeletons'
export default function NewCustomsJobPage() {
  const params = useParams<{ id: string; shipmentId: string }>(); const router = useRouter(); const [shipment, setShipment] = useState<Shipment | null>(null); const [quantities, setQuantities] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const loadingStartedAt = useRef(Date.now())
  useEffect(() => { loadingStartedAt.current = Date.now(); getShipment(params.shipmentId).then((loaded) => finishLoadingAfterMinimum(loadingStartedAt.current, () => setShipment(loaded))) }, [params.shipmentId])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (!shipment) return; const allocations = shipment.allocations.flatMap((item) => { const quantity = Number(quantities[item.ciplItemId] || 0); return quantity > 0 ? [{ ciplItemId: item.ciplItemId, quantity, unit: item.unit }] : [] }); if (!allocations.length) return setError('Alokasikan minimal satu item ke Job.'); setSaving(true); setError(''); try { const job = await createCustomsJob(params.shipmentId, { documentType: String(form.get('documentType')) as 'BC_2_3' | 'BC_2_5' | 'BC_3_0', ajuNumber: String(form.get('ajuNumber') || '').trim() || null, registrationNumber: null, registrationDate: null, customsOfficeCode: String(form.get('customsOfficeCode') || '').trim().toUpperCase() || null, warehouseId: null, warehouseName: null, assignedToId: null, billing: { kind: 'NOT_READY' }, status: 'DRAFT', attachments: [], notes: String(form.get('notes') || '').trim() || null }, allocations); router.push(`/cipls/${params.id}/shipments/${params.shipmentId}/jobs/${job.id}`) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Job tidak dapat dibuat.') } finally { setSaving(false) } }
  if (!shipment) return <ListSkeleton />
  return <div className="mx-auto max-w-3xl"><form onSubmit={submit} className="card p-6 sm:p-8"><h1 className="text-2xl font-bold">Buat Customs Job</h1><p className="mt-2 text-sm text-slate-500">Satu Job merekam satu dokumen BC dan mengambil item dari Shipment ini.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="label">Jenis dokumen BC<select name="documentType" className="input mt-1"><option value="BC_2_3">BC 2.3</option><option value="BC_2_5">BC 2.5</option><option value="BC_3_0">BC 3.0</option></select></label><label className="label">Nomor aju (opsional)<input name="ajuNumber" className="input mt-1" /></label><label className="label">Kode kantor pabean<input name="customsOfficeCode" className="input mt-1" maxLength={20} /><span className="mt-1 block text-xs text-slate-500">Diperlukan untuk detail CEISA, TPS, dan manifes.</span></label><label className="label sm:col-span-2">Catatan<textarea name="notes" className="input mt-1 min-h-24" /></label></div><section className="mt-6"><h2 className="font-semibold">Alokasi item</h2><div className="mt-3 space-y-3">{shipment.allocations.map((item) => <label key={item.ciplItemId} className="flex items-center justify-between gap-4"><span>{item.ciplItemId} <span className="text-sm text-slate-500">({item.quantity} {item.unit})</span></span><input type="number" min="0" max={item.quantity} step="any" className="input w-28" value={quantities[item.ciplItemId] ?? ''} onChange={(event) => setQuantities((current) => ({ ...current, [item.ciplItemId]: event.target.value }))} /></label>)}</div></section>{error && <p className="mt-4 text-sm font-medium text-rose-700">{error}</p>}<button disabled={saving} className="btn-primary mt-6">{saving ? 'Menyimpan…' : 'Buat Job'}</button></form></div>
}
