-- Replace the payload-backed personal board with a typed, auditable collaboration aggregate.
alter table public.tickets
  add column if not exists ticket_number bigint generated by default as identity,
  add column if not exists creator_id uuid references public.app_users(id) on delete set null,
  add column if not exists assignee_id uuid references public.app_users(id) on delete set null,
  add column if not exists context_kind text,
  add column if not exists context_id text,
  add column if not exists title text,
  add column if not exists description text,
  add column if not exists status text,
  add column if not exists sort_order integer,
  add column if not exists priority text,
  add column if not exists completion_note text,
  add column if not exists completed_at timestamptz,
  add column if not exists updated_by_id uuid references public.app_users(id) on delete set null,
  add column if not exists last_activity_at timestamptz not null default now();

-- Preserve legacy rows even when the old payload cannot establish attribution.
update public.tickets
set
  context_kind = coalesce(context_kind, case when payload->'context'->>'kind' in ('EVENT', 'JOB') then payload->'context'->>'kind' else 'GENERAL' end),
  context_id = coalesce(context_id, case when payload->'context'->>'kind' in ('EVENT', 'JOB') then nullif(payload->'context'->>'id', '') else null end),
  title = coalesce(title, nullif(trim(payload->>'title'), ''), 'Ticket lama'),
  description = coalesce(description, nullif(trim(payload->>'description'), '')),
  status = coalesce(status, nullif(payload->>'status', ''), 'TODO'),
  sort_order = coalesce(sort_order, nullif(payload->>'order', '')::integer, 1),
  priority = coalesce(priority, nullif(payload->>'priority', ''), 'NORMAL'),
  completion_note = coalesce(completion_note, nullif(payload->'completion'->>'note', '')),
  completed_at = coalesce(completed_at, nullif(payload->'completion'->>'completedAt', '')::timestamptz),
  last_activity_at = coalesce(last_activity_at, updated_at, created_at)
where context_kind is null or title is null or status is null or sort_order is null or priority is null;

update public.tickets t
set assignee_id = u.id
from public.app_users u
where t.assignee_id is null
  and (t.payload->>'assigneeId') = u.id::text;

with numbered as (
  select workspace_id, id, row_number() over (partition by workspace_id order by created_at, id) as number
  from public.tickets
)
update public.tickets t
set ticket_number = numbered.number
from numbered
where t.workspace_id = numbered.workspace_id and t.id = numbered.id;

select setval(pg_get_serial_sequence('public.tickets', 'ticket_number'), coalesce((select max(ticket_number) from public.tickets), 0) + 1, false);

alter table public.tickets
  alter column ticket_number set not null,
  alter column context_kind set not null,
  alter column title set not null,
  alter column status set not null,
  alter column sort_order set not null,
  alter column priority set not null,
  alter column last_activity_at set not null;

alter table public.tickets
  add constraint tickets_context_check check ((context_kind = 'GENERAL' and context_id is null) or (context_kind in ('EVENT', 'JOB') and context_id is not null)),
  add constraint tickets_status_check check (status in ('TODO', 'PROGRESS', 'DONE')),
  add constraint tickets_priority_check check (priority in ('NORMAL', 'URGENT')),
  add constraint tickets_sort_order_check check (sort_order > 0),
  add constraint tickets_title_not_blank check (char_length(trim(title)) > 0),
  add constraint tickets_completion_check check ((status = 'DONE' and completion_note is not null and char_length(trim(completion_note)) > 0 and completed_at is not null) or (status <> 'DONE' and completion_note is null and completed_at is null)),
  add constraint tickets_workspace_number_key unique (workspace_id, ticket_number);

create index if not exists tickets_board_idx on public.tickets (workspace_id, assignee_id, status, sort_order);
create index if not exists tickets_context_idx on public.tickets (workspace_id, context_kind, context_id);

create table if not exists public.ticket_comments (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  id uuid primary key default gen_random_uuid(),
  ticket_id text not null,
  author_id uuid not null references public.app_users(id) on delete restrict,
  body text not null check (char_length(trim(body)) > 0),
  created_at timestamptz not null default now(),
  foreign key (workspace_id, ticket_id) references public.tickets(workspace_id, id) on delete cascade
);
create index if not exists ticket_comments_timeline_idx on public.ticket_comments (workspace_id, ticket_id, created_at, id);

create table if not exists public.ticket_activities (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  id uuid primary key default gen_random_uuid(),
  ticket_id text not null,
  actor_id uuid references public.app_users(id) on delete set null,
  kind text not null check (kind in ('CREATED', 'DETAILS_CHANGED', 'ASSIGNEE_CHANGED', 'STATUS_CHANGED')),
  change jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  foreign key (workspace_id, ticket_id) references public.tickets(workspace_id, id) on delete cascade
);
create index if not exists ticket_activities_timeline_idx on public.ticket_activities (workspace_id, ticket_id, occurred_at, id);

alter table public.ticket_comments enable row level security;
alter table public.ticket_activities enable row level security;
revoke all on table public.ticket_comments, public.ticket_activities from anon, authenticated;

create or replace function public.record_ticket_activity() returns trigger language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    insert into public.ticket_activities (workspace_id, ticket_id, actor_id, kind, change, occurred_at)
    values (new.workspace_id, new.id, new.creator_id, 'CREATED', '{}'::jsonb, new.created_at);
    return new;
  end if;
  if new.title is distinct from old.title or new.description is distinct from old.description or new.priority is distinct from old.priority or new.context_kind is distinct from old.context_kind or new.context_id is distinct from old.context_id then
    insert into public.ticket_activities (workspace_id, ticket_id, actor_id, kind, change)
    values (new.workspace_id, new.id, new.updated_by_id, 'DETAILS_CHANGED', jsonb_build_object('fields', (
      select jsonb_agg(value) from jsonb_array_elements(array_remove(array[
        case when new.title is distinct from old.title then jsonb_build_object('field','TITLE','before',old.title,'after',new.title) end,
        case when new.description is distinct from old.description then jsonb_build_object('field','DESCRIPTION','before',old.description,'after',new.description) end,
        case when new.priority is distinct from old.priority then jsonb_build_object('field','PRIORITY','before',old.priority,'after',new.priority) end,
        case when new.context_kind is distinct from old.context_kind or new.context_id is distinct from old.context_id then jsonb_build_object('field','CONTEXT','before',case when old.context_kind = 'GENERAL' then 'GENERAL' else old.context_kind || ':' || old.context_id end,'after',case when new.context_kind = 'GENERAL' then 'GENERAL' else new.context_kind || ':' || new.context_id end) end
      ], null)) value)));
    new.last_activity_at := now();
  end if;
  if new.assignee_id is distinct from old.assignee_id then
    insert into public.ticket_activities (workspace_id, ticket_id, actor_id, kind, change)
    values (new.workspace_id, new.id, new.updated_by_id, 'ASSIGNEE_CHANGED', jsonb_build_object('before', old.assignee_id, 'after', new.assignee_id));
    new.last_activity_at := now();
  end if;
  if new.status is distinct from old.status then
    insert into public.ticket_activities (workspace_id, ticket_id, actor_id, kind, change)
    values (new.workspace_id, new.id, new.updated_by_id, 'STATUS_CHANGED', jsonb_build_object('before', old.status, 'after', new.status, 'note', coalesce(new.completion_note, null)));
    new.last_activity_at := now();
  end if;
  return new;
end $$;

drop trigger if exists tickets_activity_trigger on public.tickets;
create trigger tickets_activity_trigger before update on public.tickets for each row execute function public.record_ticket_activity();
create trigger tickets_created_activity_trigger after insert on public.tickets for each row execute function public.record_ticket_activity();

create or replace function public.touch_ticket_from_comment() returns trigger language plpgsql as $$
begin
  update public.tickets set last_activity_at = new.created_at where workspace_id = new.workspace_id and id = new.ticket_id;
  return new;
end $$;
drop trigger if exists ticket_comments_touch_ticket on public.ticket_comments;
create trigger ticket_comments_touch_ticket after insert on public.ticket_comments for each row execute function public.touch_ticket_from_comment();

create or replace function public.create_ticket(p_workspace_id uuid, p_actor_id uuid, p_id text, p_title text, p_description text, p_context_kind text, p_context_id text, p_priority text, p_assignee_id uuid) returns public.tickets language plpgsql as $$
declare result public.tickets;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_workspace_id::text || coalesce(p_assignee_id::text, 'unassigned') || 'TODO', 0));
  insert into public.tickets (workspace_id, id, creator_id, assignee_id, context_kind, context_id, title, description, status, sort_order, priority, updated_by_id)
  values (p_workspace_id, p_id, p_actor_id, p_assignee_id, p_context_kind, p_context_id, trim(p_title), nullif(trim(p_description), ''), 'TODO', coalesce((select max(sort_order) + 1 from public.tickets where workspace_id = p_workspace_id and assignee_id is not distinct from p_assignee_id and status = 'TODO'), 1), p_priority, p_actor_id)
  returning * into result;
  return result;
end $$;

create or replace function public.edit_ticket(p_workspace_id uuid, p_actor_id uuid, p_ticket_id text, p_title text, p_description text, p_context_kind text, p_context_id text, p_priority text, p_assignee_id uuid) returns public.tickets language plpgsql as $$
declare result public.tickets;
begin
  update public.tickets set title = trim(p_title), description = nullif(trim(p_description), ''), context_kind = p_context_kind, context_id = p_context_id, priority = p_priority, assignee_id = p_assignee_id, updated_by_id = p_actor_id, updated_at = now() where workspace_id = p_workspace_id and id = p_ticket_id returning * into result;
  if not found then raise exception 'Ticket tidak ditemukan.' using errcode = 'P0002'; end if;
  return result;
end $$;

create or replace function public.assign_ticket(p_workspace_id uuid, p_actor_id uuid, p_ticket_id text, p_assignee_id uuid) returns public.tickets language plpgsql as $$
declare result public.tickets;
begin
  update public.tickets set assignee_id = p_assignee_id, sort_order = coalesce((select max(sort_order) + 1 from public.tickets where workspace_id = p_workspace_id and assignee_id is not distinct from p_assignee_id and status = (select status from public.tickets where workspace_id = p_workspace_id and id = p_ticket_id)), 1), updated_by_id = p_actor_id, updated_at = now() where workspace_id = p_workspace_id and id = p_ticket_id returning * into result;
  if not found then raise exception 'Ticket tidak ditemukan.' using errcode = 'P0002'; end if;
  return result;
end $$;

create or replace function public.move_ticket(p_workspace_id uuid, p_actor_id uuid, p_ticket_id text, p_status text, p_ordered_ticket_ids text[], p_completion_note text, p_reopen_reason text) returns public.tickets language plpgsql as $$
declare result public.tickets;
begin
  update public.tickets set status = p_status, completion_note = case when p_status = 'DONE' then nullif(trim(p_completion_note), '') else null end, completed_at = case when p_status = 'DONE' then now() else null end, updated_by_id = p_actor_id, updated_at = now() where workspace_id = p_workspace_id and id = p_ticket_id returning * into result;
  if not found then raise exception 'Ticket tidak ditemukan.' using errcode = 'P0002'; end if;
  if p_ordered_ticket_ids is not null then
    update public.tickets t set sort_order = ordered.ordinality, updated_at = now()
    from unnest(p_ordered_ticket_ids) with ordinality as ordered(id, ordinality)
    where t.workspace_id = p_workspace_id and t.id = ordered.id;
  end if;
  return result;
end $$;

-- No generic payload path remains for ticket writes.
alter table public.tickets drop column if exists payload;
